apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: gbengaps/udagram-api-feed:v1
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:
              name: microservice-secret
